version: '3.0'

services:
  app:
    container_name: app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: php:7.2-apache
    volumes:
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./app/src:/var/www/html
    ports:
      - 8080:80
    networks:
      backend:

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack/init:/docker-entrypoint-initaws.d"
      - "./docker/localstack/tmp:/tmp/localstack"
    # NOTE: sdk経由でs3にアクセスする際のhost解決のために設定
    networks:
      backend:
        aliases:
          - sample-bucket.localstack

networks:
  backend: